/*using Microsoft.VisualStudio.TestTools.UnitTesting;
using ConsoleAppProject.App03;
namespace ConsoleApp.Tests
{
	[TestClass]

	public class TestStudentGrades
	{ 

        private readonly StudentGrades conveter = new StudentGrades();

		[TestMethod]

        public void TestCovert0ToGradeF()
		{ 
			// Arange

			Grades expectedGrade = Grades.F;

			//Act

			Grades actualGrade = conveter.ConverterToGrade(0);

			// Assert

			Assert.AreEqual(expectedGrade, actualGrade);

		}

    }
}*/

